---
name: Timothy
surname: Hyndman
position: Data Scientist
address: Melbourne, Australia
date: "`r format(Sys.time(), '%B %Y')`"
profilepic: naturetimcrop.jpg
www: timothyhyndman.com
email: timothy.hyndman@gmail.com
# twitter: mariecurie
github: timothyhyndman
# linkedin: mariecurie
# aboutme: about me
docname: curriculum vitae
# phone: +61 423065048
output: vitae::awesomecv
header-includes:
  - \definecolor{awesome}{HTML}{246078}
  - \renewcommand*{\sectionstyle}[1]{{\fontsize{16pt}{1em}\bodyfont\bfseries\textcolor{awesome}{#1}}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

<!-- # Professional summary -->
<!--  * I am good -->

# Education
```{r}
tribble(
  ~ degree, ~ dates, ~ institution, ~ loc, ~ details,
    "Ph.D.", "2015 -- 2019", "University of Melbourne", "Melbourne, Australia", "Thesis: `The coupling time for the Ising heat-bath dynamics & efficient optimization for statistical inference'.",
  "Ph.D.", "2015 -- 2019", "University of Melbourne", "Melbourne, Australia", "Completed under the supervision of Prof. Peter Taylor, Prof. Aurore Delaigle, and Assoc. Prof. Tim Garoni.",
  # "B.Sc.(Hons)", "2011-2014", "Monash University", "Clayton, Australia", "Recipient of the Monash science merit scholarship (2011), multiple dean's list fellowship awards (2012, 2013, 2014), the Monash jubilee honours scholarship (2014), and the university medal for undergraduate academic excellence (2015).",
  "B.Sc.(Hons)", "2011 -- 2014", "Monash University", "Clayton, Australia", "Honours thesis: proved that a Markov chain with close ties to the Ising model (the `worm chain') was rapidly mixing.",
  "B.Sc.(Hons)", "2011 -- 2014", "Monash University", "Clayton, Australia", "GPA of 3.957, H1 honours result with an average mark of 93."
) %>%
  detailed_entries(degree, dates, institution, loc, details)
```

```{r}
tribble(
  ~ degree, ~ dates, ~ institution, ~ loc,
"A.Mus.A (Piano)", "2011", "Australian Music Examinations Board", "Melbourne, Australia"
) %>%
  detailed_entries(degree, dates, institution, loc)
```

# Employment History
```{r employment}
tribble(
  ~ role, ~ company, ~ loc, ~ dates, ~ details,
  "Senior Statistician", "Predictive Analytics Group", "WFH", "Jan. 2021 - Present", "Lead developer, mathematician, and architect for a generalised sports schedule optimiser. Starting with a legacy codebase created for a specific client problem, I generalised the optimiser to work for a large variety of sports scheduling problems, while improving the speed by a factor of over 500. I worked with backend, frontend, and design teams to build a web-app around the application. I independently designed and implemented creative solutions to allow for non-technical users to specify hugely varied constraints for highly diverse sports schedules. I implemented novel generalisations of methods from the academic literature and provided overall direction for new feature development to senior management.",
  "Senior Statistician", "Predictive Analytics Group", "WFH", "Jan. 2021 - Present", "Supervised, trained, and mentored junior staff on a project implementing new data structures in our sports scheduler which resulted in a cleaner and more efficient codebase. My teaching resulted in the junior staff producing a higher code quality and acting with greater independence.",
  "Senior Statistician", "Predictive Analytics Group", "WFH", "Jan. 2021 - Present", "Researched and orchestrated a collection of AWS services to automatically process registration data for a large sports organisation and use it to update a live dashboard. I used AWS SAM to define the infrastructure as code, and migrated old manually managed services to use this new structure.",
  "Data scientist", "Biarri", "Windsor, Australia", "May. 2019 - Dec. 2020", "Technical lead on a project with one of Australia's major fuel retailers to recommend real-time fuel prices at over 500 stores. Starting with over 100 GB of raw transaction data, I developed predictive models for short term fuel volume forecasts at candidate prices, as well as predictive models for in-store purchases and long term effects of difference pricing strategies. I was one of two developers for the final software, and helped deploy the solution to the client's Azure infrastructure. The solution is being used Australia wide.",
  "Data scientist", "Biarri", "Windsor, Australia", "May. 2019 - Dec. 2020", "Developed tool to suggest `optimal' markdown prices for a group of sports and outdoor retailers. The challenge was to recommend a price that would allow them to sell stock within an allocated time while maximising profit. After two trial implementations, the net increase in margin was measured at approximately $200k or 20%.",
  "Data scientist", "Biarri", "Windsor, Australia", "May. 2019 - Dec. 2020", "Received feedback that we were `the best value client we have ever had' by a large government organisation for my analytics work on one of their processing pipelines.",
  "Data scientist", "Biarri", "Windsor, Australia", "May. 2019 - Dec. 2020", "I have also developed ranking algorithms for a competitive form of Poker, produced a performance analysis on a 3rd party's electricity forecasting algorithms, and determined factors that correlated with poor sales growth for an outdoor activities retailer.",
  # "Statistical Consultant", "Biarri", "Windsor, Australia", "Nov. 2018", "Two week internship as a statistical consultant for Biarri optimisation. I delivered analysis on a client's sales data and identified factors that correlated with poor sales growth. The project involved cleaning and wrangling approximately 20GB of data; aggregating relevant data appropriately; using techniques such as seasonal trend decomposition, arima models, and regression models; and presenting these result in an intuitive graphical way.",
  "Research assistant", "Monash University", "Clayton, Australia", "2019", "Worked with Assoc. Prof. Tim Garoni on improving the results proved in my thesis. The outcome of this work, combined with the relevant parts from my thesis, is a working paper (detailed below).",
  "Tutor", "Monash University/University of Melbourne", "Melbourne, Australia", "2013 -- 2018", "Tutored linear algebra (MAST10007), analysis of change (MTH1020) and differential geometry (MTH3110). Mentioned in student evaluations as one of the best parts of the differential geometry unit."
  # "Teaching Associate", "", "Clayton, Australia", "2013 -- 2014", "
  # "AMSI Summer Research Scholarship", "Monash University", "Clayton, Australia", "2012 -- 2013", "Supervised by Prof. Kate Smith-Miles and Dr Davaatseren Baatar. Worked on optimising an instrument scheduler for Leica Microsystems.",
  # "Mathematics and English Tutoring", "Private", "Melbourne, Australia", "2009-2015", "Tutored students from years 7 to 12.",
  # "Piano Accompanist", "Luther College", "Croydon, Australia", "2010-2013", "",
  # "Piano Teaching", "Private", "Melbourne, Australia", "2009-2015", ""
) %>%
  detailed_entries(role, dates, company, loc, details)
```

\newpage
# Relevant Skills
```{r skills}
tribble(
  ~skilltype, ~skillslist,
  "Programming", "Python, R, MATLAB, SQL, Bash, JavaScript, HTML, CSS, C++",
  "Libraries", "Pandas, Numpy, Scipy, Numba, Tensorflow, OpenCV, Scikit-learn",
  "Tools", "Git, Docker, LaTeX",
  "AWS", "S3, Athena, Lambda, Quicksight, SAM, Secrets, SageMaker"
  # "ML Skills", "GAMs, "
) %>% detailed_entries(what=skillslist, with=skilltype)
```


# Software (R Packages)
```{r r-pkgs}
tribble(
  ~ pkg, ~ when, ~ role, ~ details, ~url,
  "fable", "2022", "Contributor", "Tidy time series forecasting", "https://github.com/tidyverts/fable",
  "cricketdata", "2022", "Author", "International cricket data for men and women, Tests, ODIs, and T20s.","https://github.com/ropenscilabs/cricketdata",
  "icons", "2021", "Contributor", "Embed SVG icons in R documents such as slides, reports and apps.","https://github.com/ropenscilabs/icon",
  "deconvolve", "2018", "Lead developer", "Provides tools for performing non-parametric deconvolution of measurement error problems","https://github.com/timothyhyndman/deconvolve",
) %>%
  brief_entries(glue::glue("\\textbf{\\href{<url>}{<pkg>}}: <role> \\newline <details>", .open = "<", .close = ">"), when, .protect = FALSE)
```

<!-- # Other awards -->
# Awards & Achievements
## Awards
```{r}
tribble(
  ~ award, ~ from, ~ year,
  "Winner of the annual `Power of Mathematics' award", "Biarri Optimisation", "2020",
  "Science Dean's list Fellowship", "Monash University", "2012 -- 2014",
  "Premier's VCE award for mathematics", "VCAA", "2011",
  "Australian Student Prize", "VCAA", "2010",
  "Australian Defence Force Long Tan Leadership and Teamwork award", "ADF", "2010"
) %>%
  brief_entries(award, year, from)
```

## Scholarships
```{r}
tribble(
  ~ award, ~ from, ~ year,
  "ACEMS top-up scholarship", "ACEMS", "2015",
  "Australian Postgraduate Award", "Australian Government", "2015",
  "Monash jubilee honours scholarship", "Monash University", "2014",
  "Science merit scholarship", "Monash University", "2011"
) %>%
  brief_entries(award, year, from)
```

## Competitions
```{r}
tribble(
  ~ award, ~ from, ~ year,
  "Winner `Advanced sampling & exploration competition'", "ACEMS", "2017",
  "Special mention `Advanced sampling & exploration competition'", "ACEMS", "2016",
  "Winner `Advanced sampling & exploration competition'", "ACEMS", "2015"
) %>%
  brief_entries(award, year, from)
```

# Publications
<!-- ## PhD thesis -->

## Research papers
```{r papers}
bibliography_entries("tim.bib")
```

<!-- ## Talks -->
<!-- ```{r talks} -->
<!-- tribble( -->
<!--   ~ when, ~ event, ~ loc, ~ title, ~ details, -->
<!--   "2018", "ACEMS multiscale models workshop", "Monash University", "Using information percolation to find the coupling time for the 1D Ising.", "", -->
<!--   "2017", "Computational and Methodological Statics", "University of London", "How many point masses do we need for non-parametric deconvolution and maximum likelihood mixture densities?", "", -->
<!--   "2016", "ANZIAM Conference", "Australian National University", "How many probability masses do we need for maximum likelihood mixture densities?", "",  -->
<!--   "2016", "ACEMS Retreat", "Sydney", "3 minute talk + poster - `How many components do we need for location mixtures?'", "" -->
<!-- ) %>% detailed_entries( -->
<!--   what = event, -->
<!--   when = when, -->
<!--   with = title, -->
<!--   where = loc, -->
<!--   why = details -->
<!-- ) -->
<!-- ``` -->
